# .streamlit/secrets.toml
[snowflake]
account = "ZJAUCLZ-NPB86736"
user = "NAGARJUNASUNKARA"
password = "SaradhaReddy#96"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
